### ISSUE TITLE
Changing from char to line visual clears extmarks

### ISSUE THREAD

**Issue by bew** [mcauley-penney/visual-whitespace.nvim#12]
On 03b3c509e9378aeb29aeff3d3d053fd533cd4af4 (latest as of today)

Gif says it all:
![Peek 2024-10-16 05-43](https://github.com/user-attachments/assets/a1ae7e42-fdb1-48cf-8bd5-5a1d4466bfae)

I'm guessing you need to swap definitions of `ModeChanged` autocommands, so it will first clear then highlight

**Comment by mcauley-penney** [comment]
Thanks for opening this and for the idea about what it could be. I hadn't even thought of this case. I'll take a look at it in the morning and see if I can get it solved.

**Comment by mcauley-penney** [comment]
@bew I pushed a commit that I think fixes this. Please test it out and let me know if you spot anything!

**Comment by bew** [comment]
It works well when switching between char/line visual mode, but as soon as I go into visual block mode the non-relevant extmarks are _not_ cleared:
![Peek 2024-10-17 14-59](https://github.com/user-attachments/assets/fd7f42f6-5863-4c93-b9a1-23699aefe631)

**Comment by mcauley-penney** [comment]
Got it! In that case, I will have to clear those first and then rehighlight, like you were saying before

I realized that I forgot to push the relevant commits from main to the branch with visual block mode, so I imagine that you ported the changes yourself. Thank you for that!

Problem: I checked some cases with visual block mode and actually checked this one before pushing those commits. Trying to reproduce it now with the getregionpos branch as it is with the below commit, I'm having some trouble. Using the process you are, which appears to be `linewise`, `charwise`, `linewise`, `blockwise`, I cannot break it. 

![vis-ws_12-cannot-reproduce](https://github.com/user-attachments/assets/a6901335-6806-4295-82d3-4e31a86c238e)

**Comment by bew** [comment]
> I realized that I forgot to push the relevant commits from main to the branch with visual block mode, so I imagine that you ported the changes yourself. Thank you for that!

Actually no, I'm not using that branch, I'm on `main` 👀
so visual block mode isn't supposed to be supported, but shouldn't break like this either..

Why is the branch not merged? Is it because it's using nightly stuff? (I'm on latest stable)

**Comment by mcauley-penney** [comment]
There is the issue, yep! 

> so visual block mode isn't supposed to be supported, but shouldn't break like this either..

Yep, I need to fix that. I will work on that sometime in the next few days, it is now on my todo list.

> Why is the branch not merged? Is it because it's using nightly stuff? (I'm on latest stable)

Yes, the branch I'm working on uses `getregionpos()`, a new built-in function which is available only in nightly for now.

**Comment by mcauley-penney** [comment]
I just pushed a commit to main (53206b0e9a79f22bcabb4d24e14af0260eb1f7cb) that *should* fix this. Please let me know if it changes things!

**Comment by bew** [comment]
> I just pushed a commit to main ([53206b0](https://github.com/mcauley-penney/visual-whitespace.nvim/commit/53206b0e9a79f22bcabb4d24e14af0260eb1f7cb)) that _should_ fix this. Please let me know if it changes things!

Yess, works great now, thank you!
