### ISSUE TITLE
Feature Request: Ability to toggle on/off

### ISSUE THREAD

**Issue by kevintraver** [mcauley-penney/visual-whitespace.nvim#13]
Would be useful to have the ability to toggle this plugin on/off.

**Comment by mcauley-penney** [comment]
Sure, no problem! I'll provide a function for this.

**Comment by mcauley-penney** [comment]
I've added the `toggle()` function and the `enabled` cfg flag to enable the plugin.

~~I forgot to add documentation, so I will do that now.~~ Docs (the README) have been updated.

**Comment by kevintraver** [comment]
Nice work! Thanks!
