### ISSUE TITLE
allow users to configure using `vim.api.nvim_set_hl`

### ISSUE THREAD

**Issue by yochem** [mcauley-penney/visual-whitespace.nvim#15]
Thanks for the nice plugin! Looks neat.

I generally tend to like (n)vim-native approaches for configuration instead of plugin-specific. Therefore, it would be nice if the user (or potentially colorschemes) can configure the highlight of this group using `vim.api.nvim_set_hl(0, "VisualNonText", ...)`. Currently, this is overwritten by the line:

```lua
api.nvim_set_hl(0, 'VisualNonText', CFG['highlight'])
```

in the setup function.

I suggest one of two approaches:

1. Support both ways of configuration, something like this would do:

```lua
  local global_highlight = api.nvim_get_hl(0, { name = 'VisualNonText' })
  if not vim.tbl_isempty(global_highlight) then
    api.nvim_set_hl(0, 'VisualNonText', global_highlight)
  else
    api.nvim_set_hl(0, 'VisualNonText', CFG['highlight'])
  end
```

2. Remove / deprecate current way of setting highlight and only check previous mentioned value, defaulting to `{ link = 'Visual' }` if not defined.

If you like one of these approaches, or have another, I could open a PR for it - just wanted to check with you first.

**Comment by mcauley-penney** [comment]
I agree with your reasoning and I want to afford this ability. I would like to continue to offer the way that I do it now for two reasons:

1. Its already established, so I'm avoiding breaking changes
2. Its not a bad feature to have. This plugin is not so popular, so I don't anticipate it having support in major color schemes. I assume that most people will probably just use the option.

That being said, I love that color schemes can support plugins, and I should set the highlight for this plugin in my own color scheme.

I will pursue option 1. You can definitely open a PR if you want 💯 If you find that you don't have the time or something, I can also do it.

**Comment by yochem** [comment]
Sure, I'll submit a PR somewhere this week! 😁

**Comment by mcauley-penney** [comment]
Reviewing this today 💯
