### ISSUE TITLE
Visual whitespace is not showing up in block selection mode

### ISSUE THREAD

**Issue by fnune** [mcauley-penney/visual-whitespace.nvim#18]
Here it is working great on line-wise visual mode:

![image](https://github.com/user-attachments/assets/22dead6a-8917-4048-af1e-77eea7985b5c)

However when using block-wise, it does not work:

![image](https://github.com/user-attachments/assets/74e3f8d2-fc43-4bad-95cc-8b691aade85d)

This is surprising to me since there is a separate issue reporting bugs with block-wise mode, but it is not showing up at all for me (https://github.com/mcauley-penney/visual-whitespace.nvim/issues/11).

Config:

```lua
return {
  "mcauley-penney/visual-whitespace.nvim",
  config = function()
    vim.api.nvim_set_hl(0, "VisualWhitespace", { link = "Visual", default = true })
    require("visual-whitespace").setup({
      highlight = { link = "VisualWhitespace" },
    })
  end,
}
```

**Comment by mcauley-penney** [comment]
Support for blockwise mode is not included in main yet. See issue #2 for more information. 

To use it, you must switch to the `getregionpos` branch. With Lazy, you can use 

```
branch = "getregionpos"
```

**Comment by fnune** [comment]
I see, thank you!
