### ISSUE TITLE
Impossible to pass options

### ISSUE THREAD

**Issue by davmacario** [mcauley-penney/visual-whitespace.nvim#23]
I believe commit [3555f3b](https://github.com/mcauley-penney/visual-whitespace.nvim/commit/3555f3b83e231385e64959b7350b4b234c2075a8) broke the setup process.

I am using Lazy, and this is my config:

```lua
{
	"mcauley-penney/visual-whitespace.nvim",
	config = function()
		require("visual-whitespace").setup({
			highlight = { fg = "#a89984", bg = "#665c54" },
		})
	end,
}
```

The colors were correctly overridden until I updated to the last version.

I debugged locally, and realized that for some reason the call to the `setup` function in [`plugin/visual-whitespace.lua`](https://github.com/mcauley-penney/visual-whitespace.nvim/blob/main/plugin/visual-whitespace.lua) happens before the one in the Lazy config, which prevents the user settings to be applied, as the `setup` function cannot be ran again.

**Comment by davmacario** [comment]
And for the specific case of highlighting, the following happens (since [6f69d75](6f69d750de8fc8cc2db829f2835e4abfcbdd54ec)):

- The call to the `setup` function in [`plugin/visual-whitespace.lua`](https://github.com/mcauley-penney/visual-whitespace.nvim/blob/main/plugin/visual-whitespace.lua) defines the `VisualNonText` highlight group
- The second call to the `setup` function (which, as of this commit, is not prevented) will not override the highlight group, as 
  ```lua
  local global_highlight = api.nvim_get_hl(0, { name = 'VisualNonText' })
  ```
  will not return an empty object.

I am not sure as of why the `setup` call in `plugin/visual-whitespace.lua` happens before the one in my own Lazy config, though.

**Comment by mcauley-penney** [comment]
Thanks for opening this! I'm going to revert that commit from yesterday and move on back to a setup format that I used to use. I dislike messing with it how it is now

I think I'm using settings that duped me into believing that I had tested all of the cases I needed to for that commit yesterday.

**Comment by mcauley-penney** [comment]
Okay, I've made some changes. Please test it out. Its irresponsible of me to do this in main but I wanted to fix this quickly so that other people might avoid it.

**Comment by davmacario** [comment]
> Its irresponsible of me to do this in main but I wanted to fix this quickly so that other people might avoid it.

No worries, I get it :).
I can confirm it works! Thanks for the fast response!
