### ISSUE TITLE
Show zero width characters

### ISSUE THREAD

**Issue by Myzel394** [mcauley-penney/visual-whitespace.nvim#6]
First of all: GREAT PLUGIN! I absolutely love it!

Second: I think it'd be extremely useful if the plugin could also show if there are zero width characters, such as:

```
​
```

yep, you cannot see this :)

While zero width characters are very rare, it will definitely save like hours of wasted time if one can find them very quickly.

**Comment by mcauley-penney** [comment]
> First of all: GREAT PLUGIN! I absolutely love it!

Thank you! I'm glad to hear that you've found it useful.

> Second: I think it'd be extremely useful if the plugin could also show if there are zero width characters

I'm open to this 👍🏻 I just need a little more information first, and to be able to reproduce invisible zero-width characters. I've always seen zero-width spaces as `<200b>` in the buffer, which is also what I get when I copy and paste this. I'm very curious (not doubting, genuinely curious) where you are having zero-width characters that Neovim isn't showing them.

**Comment by Myzel394** [comment]
> I've always seen zero-width spaces as <200b> in the buffer, which is also what I get when I copy and paste this.

Oh well lol I guess I should try things myself before opening issues - I'm getting this too :D

Well, in this case this isn't required anymore :D

**Comment by mcauley-penney** [comment]
> Oh well lol I guess I should try things myself before opening issues

I did something like this last week in the Neovim repo lmao. Its awesome just to hear someone is actually using this, so I don't mind the issue one bit.
