### ISSUE TITLE
Error when using CRLF

### ISSUE THREAD

**Issue by Myzel394** [mcauley-penney/visual-whitespace.nvim#7]
When you have a file with CR + LF and you go to visual mode, the following error is thrown:

```
Error detected while processing ModeChanged Autocommands for "*:[vV]":
Error executing lua callback: ...im/lazy/visual-whitespace.nvim/lua/visual-whitespace.lua:104: Invalid 'col': out of range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...im/lazy/visual-whitespace.nvim/lua/visual-whitespace.lua:104: in function 'apply_marks'
        ...im/lazy/visual-whitespace.nvim/lua/visual-whitespace.lua:135: in function <...im/lazy/visual-whitespace.nvim/lua/visual-whitespace.lua:115>
```

## Reproduction

1. Open a file
2. Enable `:set fileformat=dos`
3. Enter some newlines
4. Go to visual mode

## Expected behavior

I think we should definitely show *both* charaacters (CR AND LF). We already got a character for LF. I'd recommend an arrow to the right for CR, something like:

```
⃪
```

or we could combine them into a single character like:

```
↩
```

**Comment by mcauley-penney** [comment]
Thanks for opening this! I basically never use the DOS fileformat and actually completely forgot to test on it.

Tbh, I don't know if it should be one or two characters: to the user, I think `CRLF` really just means "end of line", so I don't know if DOS fileformat users care about seeing both characters. I'm not that population tho, so I can't really say. I'll experiment with both.

**Comment by Myzel394** [comment]
>  I don't know if DOS fileformat users care about seeing both characters

I'm strongly for showing both characters. When I installed this plugin I expected this to show the "true" characters behind white space. When people deal with different kinds of file format, I think it's important that they can immediately tell if a file is CRLF or LF formatted. Especially in cases where people are debugging issues with like such cases and they don't know CRLF exists, I think this would greatly benefit them :D

**Comment by mcauley-penney** [comment]
I've hacked something together to make this *kind of* work.

![vsws_win-eol](https://github.com/mcauley-penney/visual-whitespace.nvim/assets/59481467/10de7f47-1a8c-4991-943d-c217b327931f)

So, it looks like `\r\n` extends beyond the end of the line, such that you can't really highlight it in visual mode while you're on the same line (as you can with the `CR` char in DOS and `lf` char in Unix). You will only get the `\r` character, as shown above. I'm investigating other ways to manage this. I'm going to push the hack to solve the `invalid col` issue, but will keep this open as a place to discuss progress on this.

**Comment by mcauley-penney** [comment]
e22d8508a0236f274dde39775ee127c85d30c0c0 resolves the invalid col issue for DOS files

**Comment by Myzel394** [comment]
Closing, since this got fixed
