### ISSUE TITLE
Unknown function: getregionpos

### ISSUE THREAD

**Issue by m3at** [mcauley-penney/visual-whitespace.nvim#9]
Hi, and thank you for this nice plugin.

I'm getting the error `Unknown function: getregionpos` after today's commit (91b33bba67a51ae620b106ecfc602afecb781d6c), from [this line](https://github.com/mcauley-penney/visual-whitespace.nvim/blob/91b33bba67a51ae620b106ecfc602afecb781d6c/lua/visual-whitespace.lua#L17). I'm on nvim 0.10.2_1 (latest for MacOS Sonoma 14.6.1).

Afaict the [patch to add `getregionpos`](https://github.com/neovim/neovim/pull/29032) was added on May 27, after the v0.10 release (May 10). I'm not sure of the release process for neovim, but the patch might only be available from nightly and in `v0.11` onward? In which case a solution might be to indicate that visual-whitespace.nvim requires nightly?

**Comment by marzeq** [comment]
same here. can confirm for the main arch linux package (`neovim` - version `0.10.2`) [`1c50443`](https://github.com/mcauley-penney/visual-whitespace.nvim/commit/1c50443199275580641ce129a75799714c68d258) is the latest working commit, but for the aur package `neovim-git` installing from [`HEAD`](https://github.com/mcauley-penney/visual-whitespace.nvim/commit/HEAD) works just fine

**Comment by mcauley-penney** [comment]
Thanks for the heads up! I will revert this today and move it to another branch
